### ISSUE TITLE
TypeError: ('Unsupported kernel function  ', 'bisquare')

### ISSUE THREAD

**Issue by Jerry-kiwi** [pysal/gwr#24]
```
import pysal as ps
from gwr.gwr import GWR
from spglm.family import Gaussian, Poisson


y = CASES_POOL_A.Call2017.reshape((-1,1))
X=shp[['cx3','cx5','cx6']].values
labels = ['Intercept', 'cx3', 'cx5', 'cx6']
u = shp.LAT
v = shp.LON
coords = zip(u,v)

model = GWR(coords, y, X, bw=12, family=Poisson(),fixed=False)
results = model.fit()
```

```
Traceback (most recent call last):

  File "<ipython-input-2-f5f6fbc75e94>", line 1, in <module>
    runfile('/home/www_adm/ownCloud/NNIIEM_SCIENCE/00_MAIN_THEME/01_GEN_FOR_R.py', wdir='/home/www_adm/ownCloud/NNIIEM_SCIENCE/00_MAIN_THEME')

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/www_adm/ownCloud/NNIIEM_SCIENCE/00_MAIN_THEME/01_GEN_FOR_R.py", line 141, in <module>
    model = GWR(coords, y, X, bw=12, family=Poisson(),fixed=False)

  File "/usr/local/lib/python3.5/dist-packages/gwr/gwr.py", line 205, in __init__
    self.W = self._build_W(fixed, kernel, coords, bw)

  File "/usr/local/lib/python3.5/dist-packages/gwr/gwr.py", line 221, in _build_W
    raise TypeError('Unsupported kernel function  ', kernel)

TypeError: ('Unsupported kernel function  ', 'bisquare')
```

**Comment by Ziqi-Li** [comment]
Could you try `coords = list(zip(u,v))` with the `list()` for the coordinates? This is due to a Python2to3 problem, in Python 2 `zip()` returns a list but in Python3 it returns an iterator, and `GWR._build_W` needs a list. 

@TaylorOshan We fixed this in tests, but shall we just enforce the coords in `GWR(__init__)` where `self.coords = coords` => `self.coords = list(coords)`

**Comment by Jerry-kiwi** [comment]
Yes, it's fixed problem
Thanks.

**Comment by Ziqi-Li** [comment]
@Jerry-kiwi 
Cool! I will close this.

**Comment by TaylorOshan** [comment]
Yea @Ziqi-Li , that seems reasonable to me. We should probably think about a better try/except block, because if buildW fails at all, it always throws that ambiguos unsupported kernel function error
